// Code generated by Icestudio 0.7.1w202108280708

`default_nettype none

//---- Top entity
module main (
 input [7:0] v83e377,
 input [2:0] ve091bd,
 output [7:0] v237199
);
 wire [0:7] w0;
 wire [0:7] w1;
 wire [0:2] w2;
 assign w0 = v83e377;
 assign v237199 = w1;
 assign w2 = ve091bd;
 main_v5874e0 v5874e0 (
  .i_ptrn(w0),
  .d_ptable0(w1),
  .fila_in(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- NameTable SMario  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Name Table of a SuperMario screen
/*-------------------------------------------------*/

module main_v5874e0 (
 input [7:0] i_ptrn,
 input [2:0] fila_in,
 output [7:0] d_ptable0
);
 // @include smario_traspas_patronbg_0.v
 wire [10:0] addr_ptable;
 
 assign addr_ptable = {i_ptrn,fila_in};
 
 ROM_PTABLE_MARIO_TRASPAS_BG_PLN0 PTABLE0
 (
   .addr(addr_ptable),
   .dout(d_ptable0)
 );
endmodule
