// Code generated by Icestudio 0.7.1w202108280708

`default_nettype none

//---- Top entity
module main (
 input va90334,
 input v2cb7a3,
 output v4e6402,
 output [1:0] v8514bc,
 output v712bbf,
 output [1:0] v2cf531,
 output [1:0] v62c682
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire [0:9] w5;
 wire [0:9] w6;
 wire w7;
 wire [0:1] w8;
 wire [0:1] w9;
 wire [0:1] w10;
 wire [0:9] w11;
 wire [0:7] w12;
 assign w1 = v2cb7a3;
 assign w2 = va90334;
 assign v4e6402 = w3;
 assign v712bbf = w4;
 assign v8514bc = w8;
 assign v2cf531 = w9;
 assign v62c682 = w10;
 vd8d107 v820333 (
  .vc82b22(w0),
  .va8051c(w1)
 );
 vec49d1 v2c74e1 (
  .v7aec70(w0),
  .v12e5c2(w2),
  .v7688c4(w3),
  .v7af556(w4),
  .v9459b8(w5),
  .vb50967(w6)
 );
 main_vdf3f26 vdf3f26 (
  .col(w5),
  .fila(w6),
  .col9(w7),
  .dir_ntable(w11)
 );
 main_v0dc009 v0dc009 (
  .col9(w7),
  .red(w8),
  .green(w9),
  .blue(w10),
  .num_patron(w12)
 );
 vac2f61 v9ca642 (
  .ve7cb90(w11),
  .v237199(w12)
 );
endmodule

/*-------------------------------------------------*/
/*--   */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- 
/*-------------------------------------------------*/
//---- Top entity
module vd8d107 (
 input va8051c,
 output vc82b22
);
 wire w0;
 wire w1;
 assign w0 = va8051c;
 assign vc82b22 = w1;
 vd8d107_v3ead23 v3ead23 (
  .clk_brd(w0),
  .clk50mhz(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- pll12to50mhz  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Generates a 50MHz clock from a 12MHz clock
/*-------------------------------------------------*/

module vd8d107_v3ead23 (
 input clk_brd,
 output clk50mhz
);
   // Generates a 50 MHz clock from a 12MHz clock
    SB_PLL40_CORE
             #(.FEEDBACK_PATH("SIMPLE"),
                 .PLLOUT_SELECT("GENCLK"),
                 .DIVR(4'd5),
                 .DIVF(6'd49),
                 .DIVQ(3'd1),
                 .FILTER_RANGE(3'b001)
             )
             uut
             (
                 .REFERENCECLK(clk_brd),
                 .PLLOUTCORE(clk50mhz),
                 .RESETB(1'b1),
                 .BYPASS(1'b0)
              );
endmodule
//---- Top entity
module vec49d1 (
 input v12e5c2,
 input v7aec70,
 output v27278a,
 output v7688c4,
 output v7af556,
 output [9:0] v9459b8,
 output [9:0] vb50967
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire [0:9] w4;
 wire [0:9] w5;
 wire w6;
 assign w0 = v12e5c2;
 assign v27278a = w1;
 assign v7688c4 = w2;
 assign v7af556 = w3;
 assign v9459b8 = w4;
 assign vb50967 = w5;
 assign w6 = v7aec70;
 vec49d1_v9a5c44 v9a5c44 (
  .rst(w0),
  .visible(w1),
  .hsinc(w2),
  .vsinc(w3),
  .col(w4),
  .fila(w5),
  .clk50mhz(w6)
 );
endmodule

/*-------------------------------------------------*/
/*-- VGA SYNC  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Generate synchronization signals for VGA 640x480 at clk 50MHz
/*-------------------------------------------------*/

module vec49d1_v9a5c44 (
 input rst,
 input clk50mhz,
 output visible,
 output hsinc,
 output vsinc,
 output [9:0] col,
 output [9:0] fila
);
 // @include vga_sync_50mhz.v
 
    vga_sync i_vga 
    (
      .rst     (rst),
      .clk     (clk50mhz),
      .visible (visible),
      //.new_pxl (new_pxl),
      .hsync   (hsinc),
      .vsync   (vsinc),
      .col     (col),
      .row     (fila)
   );
 
endmodule
//---- Top entity
module vac2f61 (
 input [9:0] ve7cb90,
 output [7:0] v237199
);
 wire [0:9] w0;
 wire [0:7] w1;
 assign w0 = ve7cb90;
 assign v237199 = w1;
 vac2f61_v5874e0 v5874e0 (
  .dir_ntable(w0),
  .num_patron(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- NameTable SMario  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Name Table of a SuperMario screen
/*-------------------------------------------------*/

module vac2f61_v5874e0 (
 input [9:0] dir_ntable,
 output [7:0] num_patron
);
 // @include smario_traspas_nt_nt0.v
 
 ROM_NTABLE_SMARIO_TRASPAS NTABLE
 (
   .addr(dir_ntable),
   .dout(num_patron)
 );
endmodule

module main_vdf3f26 (
 input [9:0] col,
 input [9:0] fila,
 output [9:0] dir_ntable,
 output col9
);
 // Generate the address for the Name Table memory
 
 //assign cuad_col = col[8:4];
 //assign cuad_fila = fila[8:4];
 assign dir_ntable = {fila[8:4], col[8:4]};
 // useful to know when we are over column 511
 assign col9 = col[9];
endmodule

module main_v0dc009 (
 input [7:0] num_patron,
 input col9,
 output [1:0] red,
 output [1:0] green,
 output [1:0] blue
);
  reg [1:0] rojo, verde, azul;
  assign red = rojo;
  assign green = verde;
  assign blue = azul;
  
  always @(*)
   begin
     rojo   = 2'b00;
     verde  = 2'b00;
     azul   = 2'b00;
     //if (visible) begin
       if (col9 == 1'b0) begin  // less than 512
         rojo  = ~num_patron [7:6];
         //verde = ~num_patron [7:6];
         verde = num_patron [5:4]; //instead of num_patron [7:6], to have more colors
         //azul  = ~num_patron [7:6];
         azul  = num_patron [3:2]; //instead of num_patron [7:6], to have more colors
       end
     //end
   end
endmodule
