// Code generated by Icestudio 0.7.1w202108280708

`default_nettype none

//---- Top entity
module main (
 input [9:0] ve7cb90,
 output [7:0] v237199
);
 wire [0:9] w0;
 wire [0:7] w1;
 assign w0 = ve7cb90;
 assign v237199 = w1;
 main_v5874e0 v5874e0 (
  .dir_ntable(w0),
  .num_patron(w1)
 );
endmodule

/*-------------------------------------------------*/
/*-- NameTable SMario  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Name Table of a SuperMario screen
/*-------------------------------------------------*/

module main_v5874e0 (
 input [9:0] dir_ntable,
 output [7:0] num_patron
);
 // @include smario_traspas_nt_nt0.v
 
 ROM_NTABLE_SMARIO_TRASPAS NTABLE
 (
   .addr(dir_ntable),
   .dout(num_patron)
 );
endmodule
