// Code generated by Icestudio 0.7.1w202108280708

`default_nettype none

//---- Top entity
module main (
 input [4:0] v6a586c,
 input [4:0] v86d61f,
 output [7:0] v237199
);
 wire [0:7] w0;
 wire [0:4] w1;
 wire [0:4] w2;
 assign v237199 = w0;
 assign w1 = v6a586c;
 assign w2 = v86d61f;
 main_v5874e0 v5874e0 (
  .num_patron(w0),
  .fila_cuad(w1),
  .col_cuad(w2)
 );
endmodule

/*-------------------------------------------------*/
/*-- NameTable SMario sports  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Name Table of a SuperMario screen, input ports are split in grid col & row
/*-------------------------------------------------*/

module main_v5874e0 (
 input [4:0] fila_cuad,
 input [4:0] col_cuad,
 output [7:0] num_patron
);
 // @include smario_traspas_nt_nt0.v
 
 wire [9:0] dir_ntable;
 
 assign dir_ntable = {fila_cuad, col_cuad};
 
 ROM_NTABLE_SMARIO_TRASPAS NTABLE
 (
   .addr(dir_ntable),
   .dout(num_patron)
 );
endmodule
