// Code generated by Icestudio 0.7.1w202108280708

`default_nettype none

//---- Top entity
module main (
 input [7:0] va264a3,
 input v7c7bf8,
 input v5074f5,
 output [1:0] va48225,
 output [1:0] v0d0802,
 output [1:0] v1ad6a6
);
 wire [0:7] w0;
 wire w1;
 wire w2;
 wire [0:1] w3;
 wire [0:1] w4;
 wire [0:1] w5;
 assign w0 = va264a3;
 assign w1 = v7c7bf8;
 assign w2 = v5074f5;
 assign va48225 = w3;
 assign v0d0802 = w4;
 assign v1ad6a6 = w5;
 main_v5874e0 v5874e0 (
  .num_patron(w0),
  .col9(w1),
  .visible(w2),
  .red(w3),
  .green(w4),
  .blue(w5)
 );
endmodule

/*-------------------------------------------------*/
/*-- Name Table Pixel generator  */
/*-- - - - - - - - - - - - - - - - - - - - - - - --*/
/*-- Pixel generation with just the NameTable 
/*-------------------------------------------------*/

module main_v5874e0 (
 input [7:0] num_patron,
 input col9,
 input visible,
 output [1:0] red,
 output [1:0] green,
 output [1:0] blue
);
  reg [1:0] rojo, verde, azul;
  assign red = rojo;
  assign green = verde;
  assign blue = azul;
  
  always @(*)
   begin
     rojo   = 2'b00;
     verde  = 2'b00;
     azul   = 2'b00;
     if (visible) begin
       if (col9 == 1'b0) begin  // less than 512
         rojo  = ~num_patron [7:6];
         //verde = ~num_patron [7:6];
         verde = num_patron [5:4]; //instead of num_patron [7:6], to have more colors
         //azul  = ~num_patron [7:6];
         azul  = num_patron [3:2]; //instead of num_patron [7:6], to have more colors
       end
     end
   end
endmodule
