ppm2rom:
	gcc -ansi -o ppm2rom.exe ppm2rom.c

# Antiguos
raw2rom:
	gcc -ansi -o raw2rom.exe raw2rom.c

rawrgb2rom:
	gcc -ansi -o rawrgb2rom.exe rawrgb2rom.c

clean:
	rm raw2rom.exe rawrgb2rom.exe ppm2rom.exe
